### PR TITLE
feat: Highlight map keys as keywords

### PR DESCRIPTION
**Pull request by syyyr**
This is something that the original queries did and IMHO it makes everything quite a lot more readable:

Before:
image
After:
image

It doesn't work for metadata string keys unfortunately and it seems that it is because 21cbe635c7cd78f429374d57ac73bbee8cec4f15 removed the `mpair` thingy:
image

### CODE REVIEW

**Comment by syyyr** [comment]
Nevermind, I figured it out. This is how it looks now:
image

**Comment by syyyr** [comment]
I fixed up the tests also. However, it seems that the highlights have some quirk: it seems that in my editor (neovim), mapping the keys to keyword at the end of the query file works. However, the highlight test still passes. If I move the queries near the top of the file, the test correctly highlights keys as keywords, but it then it doesn't work in neovim. I'm not sure why that is.

**Comment by amaanq** [comment]
Hi, sorry for just seeing this! I don't think `@keyword` fits, we can go the route of json by having it be `@label` instead. I'll push that shortly!

**Comment by amaanq** [comment]
Updated now

**Comment by syyyr** [comment]
Thanks!

**Pull request closed without merging**
